name: reader_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^2.1.0
  flutter_easyrefresh: ^1.2.7
  cupertino_icons: ^0.1.2
  banner: ^0.1.3
  cached_network_image: ^0.7.0
  adsorptionview_flutter: ^0.1.3
  sqflite: ^1.1.0
  intl: ^0.15.8
  fluttertoast: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/

